name: Publish

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        TESTINGPLATFORM_TELEMETRY_OPTOUT: 1

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          8.0.x
          10.0.x
        global-json-file: global.json

    - name: Test
      run: dotnet test --solution CurlyRpc.slnx -c Release

    - name: Pack with dotnet
      run: |
        # Strip leading 'v' if present
        VERSION="${GITHUB_REF_NAME#v}"
        echo "$VERSION"
        PACKAGE_PATH="${GITHUB_WORKSPACE}/artifacts"
        dotnet pack src/CurlyRpc/CurlyRpc.csproj \
          --configuration Release \
          --property:PackageOutputPath=$PACKAGE_PATH \
          -p:Version=$VERSION \
          -p:ContinuousIntegrationBuild=True

    - name: Push with dotnet
      run: dotnet nuget push "artifacts/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
